project_id = "wmrsekgxueceaeobxuss"

[functions.notify-order-ready]
verify_jwt = false

[functions.notify-order-dispatch]
verify_jwt = false

[functions.test-cardapioweb-connection]
verify_jwt = false

[functions.test-foody-connection]
verify_jwt = false

[functions.webhook-orders]
verify_jwt = false

[functions.poll-orders]
verify_jwt = false

[functions.sync-orders-status]
verify_jwt = false

[functions.cleanup-old-orders]
verify_jwt = false

[functions.send-invitation]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.send-to-foody]
verify_jwt = false

[functions.foody-webhook]
verify_jwt = false

[functions.force-close-order]
verify_jwt = false
