project_id = "cpxuluerkzpynlcdnxcq"

[functions.redistribute-items]
verify_jwt = false
 
[functions.webhook-orders]
verify_jwt = false

[functions.printnode]
verify_jwt = false

[functions.sync-orders-status]
verify_jwt = false

[functions.process-webhook-queue]
verify_jwt = false
